routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('menus.index');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::apiResource('menus', 'MenuController');
    Route::post('/menu/{menu}/attach', 'MenuController@attach')->name('menus.attach');
    Route::post('/menu/{menu}/detach', 'MenuController@detach')->name('menus.detach');
    Route::apiResource('dishes', 'DishController');
    Route::post('/dish/{dish}/attach', 'DishController@attach')->name('dishes.attach');
    Route::post('/dish/{dish}/detach', 'DishController@detach')->name('dishes.detach');
	Route::post('/dish/{dish}/images', 'DishController@upload')->name('dishes.upload');

	Route::apiResource('products', 'ProductController');
});

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $fillable = [
        'name', 'comment',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function dishes()
    {
        return $this->belongsToMany(Dish::class);
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Dish;
use App\Menu;
use Illuminate\Http\Request;
use App\Repositories\MenuRepository;

class MenuController extends Controller
{
    protected $menus;

    public function __construct(MenuRepository $menus)
    {
        $this->menus = $menus;
    }

    public function index(Request $request)
    {

        return view('menus.index', [
                'menus' => $this->menus->forUser($request->user()),
            ]);
    }

    public function show(Menu $menu)
    {
        $dishes = $menu->dishes()->orderBy('created_at', 'desc')->paginate(10);

        $array = [];
        foreach ($dishes as $dish)
            $array[] = $dish->id;

        $all_dishes = Dish::all()->except($array);

        return view('menus.show', compact('menu','dishes','all_dishes'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255'
        ]);

        $request->user()->menus()->create(
            [
                'name' => $request->name,
                'comment' => $request->comment,
            ]
        );

        return redirect()->route('menus.index');
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:255'
        ]);

        $menu = Menu::find($id);

        $menu->name = $request->name;
        $menu->comment = $request->comment;
        $menu->save();

        return redirect()->route('menus.show', $request->id);
    }


    public function destroy(Menu $menu)
    {
        $menu->delete();

        return redirect()->route('menus.index');
    }

    public function detach(Request $request, Menu $menu)
    {
        $this->validate($request, [
            'dish' => 'integer|required|exists:dishes,id'
        ]);

        $dish = Dish::find($request->get('dish'));
        $menu->dishes()->detach($dish);

        return redirect()->route('menus.show', $menu->id);
    }

    public function attach(Request $request, Menu $menu)
    {
        $this->validate($request, [
            'dish' => 'integer|required|exists:dishes,id'
        ]);

        $dish = Dish::find($request->get('dish'));
        $menu->dishes()->attach($dish);

        return redirect()->route('menus.show', $menu->id);
    }
}

resources/views/menus/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Meniukai</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('menus.store') }}" method="post" class="form-horizontal">
                            {{ csrf_field() }}
                            <div class="form-group {{$errors->has('name') ? ' has-error' : '' }}"}}>
                                <label for="name" class="col-sm-3 control-label">Meniu pavadinimas</label>
                                <div class="col-sm-6">
                                    <input type="text" name="name" id="name" class="form-control">

                                    @if ($errors->has('name'))
                                        <div class="help-block">
                                            Įveskite pavadinimą
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group {{$errors->has('name') ? ' has-error' : '' }}"}}>
                                <label for="comment" class="col-sm-3 control-label">Komentaras</label>
                                <div class="col-sm-6">
                                    <input type="text" name="comment" id="comment" class="form-control">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-6">
                                    <button type="submit" class="btn btn-default">Pridėti</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Sąrašas:</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($menus->count())
                            <table class="table table-striped">
                                <thead>
                                    <th>Pavadinimas</th>
                                    <th>Komentaras</th>
                                    <th>&nbsp;</th>
                                </thead>
                                <tbody>
                                    @foreach ($menus as $menu)
                                        <tr>
                                            <td> <a href="{{route('menus.show', $menu->id) }}"> {{ $menu->name }} </a></td>
                                            <td> {{ $menu->comment }}</td>
                                            <td>
                                                <form action="{{ route('menus.destroy', $menu->id)}} " method="post">
                                                    <button type="submit" class="btn btn-danger">Trinti</button>
                                                    {{ method_field('DELETE') }}
                                                    {{ csrf_field() }}
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                        <p> Neturite Meniuku </p>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/menus/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Meniukas {{ $menu->name }}</div>
                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form action="{{ route('menus.update', $menu->id) }}" method="post" class="form-horizontal">
                            {{ method_field('PUT') }}
                            {{ csrf_field() }}

                            <div class="form-group {{$errors->has('name') ? ' has-error' : '' }}"}}>
                                <label for="name" class="col-sm-3 control-label">Meniu pavadinimas</label>
                                <div class="col-sm-6">
                                    <input type="text" name="name" id="name" value="{{ $menu->name }}" class="form-control">

                                    @if ($errors->has('name'))
                                        <div class="help-block">
                                            Iveskite pavadinima
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group {{$errors->has('name') ? ' has-error' : '' }}"}}>
                                <label for="comment" class="col-sm-3 control-label">Komentaras</label>
                                <div class="col-sm-6">
                                    <input type="text" name="comment" id="comment" value="{{ $menu->comment }}" class="form-control">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-6">
                                    <button type="submit" class="btn btn-default">Išsaugoti</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Prisegtų patiekalų sąrašas:</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if ($dishes->count())
                            <table class="table table-striped">
                                <thead>
                                <th>Pavadinimas</th>
                                <th>Komentaras</th>
                                <th>&nbsp;</th>
                                </thead>
                                <tbody>
                                <form action="{{ route('menus.detach', $menu->id)}} " method="post">
                                    {{ csrf_field() }}
                                @foreach ($dishes as $dish)
                                    <tr>
                                        <td> <a href="{{route('dishes.show', $dish->id) }}">{{ $dish->name }}</a></td>
                                        <td> {{ $dish->comment }}</td>
                                        <td>
                                                <button name="dish" value="{{$dish->id}}" type="submit" class="btn btn-danger">Atsegti</button>
                                        </td>
                                    </tr>
                                @endforeach
                                </form>
                                </tbody>
                            </table>
                        @else
                            <p> Patiekalas neturi prisegtų patiekalų </p>
                        @endif
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Prisegti kitą patiekalą:</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($all_dishes->count())
                            <table class="table table-striped">
                                <thead>
                                <th>Pavadinimas</th>
                                <th>Komentaras</th>
                                <th>&nbsp;</th>
                                </thead>
                                <tbody>
                                <form action="{{ route('menus.attach', $menu->id)}} " method="post">
                                    {{ csrf_field() }}
                                @foreach ($all_dishes as $dish)
                                    <tr>
                                        <td> <a href="{{route('dishes.show', $dish->id) }}">{{ $dish->name }}</a></td>
                                        <td> {{ $dish->comment }}</td>
                                        <td>
                                            <button name="dish" value="{{$dish->id}}" type="submit" class="btn btn-danger">Prisegti</button>
                                        </td>
                                    </tr>
                                @endforeach
                                </form>
                                </tbody>
                            </table>
                        @else
                            <p> Nera kitų patiekalų </p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection