routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('menus.index');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::apiResource('menus', 'MenuController');
    Route::post('/menu/{menu}/attach', 'MenuController@attach')->name('menus.attach');
    Route::post('/menu/{menu}/detach', 'MenuController@detach')->name('menus.detach');
    Route::apiResource('dishes', 'DishController');
    Route::post('/dish/{dish}/attach', 'DishController@attach')->name('dishes.attach');
    Route::post('/dish/{dish}/detach', 'DishController@detach')->name('dishes.detach');
	Route::post('/dish/{dish}/images', 'DishController@upload')->name('dishes.upload');

	Route::apiResource('products', 'ProductController');
});

app/Dish.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dish extends Model
{
    protected $fillable = [
        'name', 'comment', 'image'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot('amount');
    }

    public function menus()
    {
        return $this->belongsToMany(Menu::class);
    }
}

app/Http/Controllers/DishController.php
<?php

namespace App\Http\Controllers;

use App\Dish;
use App\Product;
use Illuminate\Http\Request;
use App\Repositories\DishRepository;
use Symfony\Component\Finder\SplFileInfo;

class DishController extends Controller
{
    protected $dishes;

    public function __construct(DishRepository $dishes)
    {
        $this->dishes = $dishes;
    }

    public function index(Request $request)
    {
        return view('dishes.index', [
                'dishes' => $this->dishes->forUser($request->user()),
            ]);
    }

    public function show(Dish $dish)
    {
        $products = $dish->products()->orderBy('created_at', 'desc')->paginate(10);

        $array = [];
        foreach ($products as $product)
            $array[] = $product->id;

        $all_products = Product::all()->except($array);

        $all_images = \File::allFiles('storage/images');
		foreach ($all_images as $key => $image)
		{
			$all_images2[$key]["name"] = $image->getRelativePathname();
			$all_images2[$key]["path"] = $image->getPath();
        }

        return view('dishes.show', compact('dish','products','all_products','all_images2'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:255'
        ]);

        $request->user()->dishes()->create(
            [
                'name' => $request->name,
                'comment' => $request->comment,
				'image' => $request->image
            ]
        );

        return redirect()->route('dishes.index');
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:255'
        ]);

        $dish = Dish::find($id);

        $dish->name = $request->name;
        $dish->comment = $request->comment;
        $dish->image = $request->image;
        $dish->save();

        return redirect()->back();
    }

    public function destroy(Dish $dish)
    {
        $dish->delete();

        return redirect()->route('dishes.index');
    }

    public function detach(Request $request, Dish $dish)
    {
        $this->validate($request, [
            'product' => 'integer|required|exists:products,id'
        ]);

        $product = Product::find($request->get('product'));
        $dish->products()->detach($product);

        return redirect()->route('dishes.show', $dish->id);
    }

    public function attach(Request $request, Dish $dish)
    {
        $this->validate($request, [
            'product' => 'integer|required|exists:products,id'
        ]);

        $product = Product::find($request->get('product'));

        $amount = $request->get('amount-'.$request->get('product'));

		$dish->products()->attach($product, array('amount' => $amount));


        return redirect()->route('dishes.show', $dish->id);
    }

    public function upload(Request $request)
	{
		$name = $request->get('name');
		$ext = $request->file('image')->guessExtension();
		$request->file('image')->storeAs('public/images', $name.'.'.$ext);

		return redirect()->back();
	}

}

resources/views/dishes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Patiekalai</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('dishes.store') }}" method="post" class="form-horizontal">
                            <div class="form-group {{$errors->has('name') ? ' has-error' : '' }}"}}>
                                <label for="name" class="col-sm-3 control-label">Patiekalo pavadinimas</label>
                                <div class="col-sm-6">
                                    <input type="text" name="name" id="name" class="form-control">

                                    @if ($errors->has('name'))
                                        <div class="help-block">
                                            Iveskite pavadinima
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group {{$errors->has('name') ? ' has-error' : '' }}"}}>
                                <label for="comment" class="col-sm-3 control-label">Komentaras</label>
                                <div class="col-sm-6">
                                    <input type="text" name="comment" id="comment" class="form-control">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-6">
                                    <button type="submit" class="btn btn-default">Pridėti</button>
                                </div>
                            </div>
                            {{ csrf_field() }}
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Sąrašas:</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($dishes->count())
                            <table class="table table-striped">
                                <thead>
                                    <th>Pavadinimas</th>
                                    <th>Komentaras</th>
                                    <th>&nbsp;</th>
                                </thead>
                                <tbody>
                                    @foreach ($dishes as $dish)
                                        <tr>
                                            <td> <a href="{{route('dishes.show', $dish->id) }}">{{ $dish->name }}</a></td>
                                            <td> {{ $dish->comment }}</td>
                                            <td>
                                                <form action="{{ route('dishes.destroy', $dish->id)}} " method="post">
                                                    <button type="submit" class="btn btn-danger">Trinti</button>
                                                    {{ method_field('DELETE') }}
                                                    {{ csrf_field() }}
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        @else
                        <p> Neturite patiekalų </p>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dishes/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Patiekalas {{ $dish->name }}</div>
                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form action="{{ route('dishes.update', $dish->id) }}" method="post" class="form-horizontal">
                            {{ method_field('PUT') }}
                            {{ csrf_field() }}
                            <div class="form-group {{$errors->has('name') ? ' has-error' : '' }}"}}>
                                <label for="name" class="col-sm-3 control-label">Patiekalo pavadinimas</label>
                                <div class="col-sm-6">
                                    <input type="text" name="name" id="name" value="{{ $dish->name }}" class="form-control">

                                    @if ($errors->has('name'))
                                        <div class="help-block">
                                            Įveskite pavadinimą
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group {{$errors->has('name') ? ' has-error' : '' }}"}}>
                                <label for="comment" class="col-sm-3 control-label">Komentaras</label>
                                <div class="col-sm-6">
                                    <input type="text" name="comment" id="comment" value="{{ $dish->comment }}" class="form-control">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="image" class="col-sm-3 control-label">Animacija</label>
                                <div class="col-sm-6">
                                    <select title="Paveiksliukas" name="image" class="selectpicker">
                                        <option>Pasirinkti...</option>
                                        @foreach ($all_images2 as $image)
                                            <option data-thumbnail="{{ asset($image["path"].'/'.$image["name"]) }}" value="{{ $image["name"] }}">{{ $image["name"] }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-6">
                                    <button type="submit" class="btn btn-default">Išsaugoti</button>
                                </div>
                            </div>
                        </form>
                    </div>
                <div class="panel-footer">
                    <div class="form-group-sm" align="center">
                        <form method="POST" action="{{ route('dishes.upload', $dish->id) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <label for="image">Atsiųsti animaciją/nuotrauką:</label>
                            <input type="file" name="image" id="image" class="alert-info">
                            Pavadinimas: <input type="text" name="name">
                            <button type="submit">Siųsti</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body" style="text-align: center">
                        @if ($dish->image)
                            <img src="{{ asset('storage/images/'.$dish->image) }}" class="animation">
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Prisegtų produktų sąrašas: <p align="right">
                            @php
                             $dish_price = 0.0;
                             foreach ($products as $product)
                                $dish_price += $product->price_single * $product->pivot->amount;
                            @endphp
                            Patiekalo kaina: {{$dish_price}} Eur
                        </p></div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if ($products->count())
                            <table class="table table-striped">
                                <thead>
                                <th>Pavadinimas</th>
                                <th>Komentaras</th>
                                <th>Kiekis</th>
                                <th>Vieneto kaina</th>
                                <th>Bendra kaina</th>
                                <th>&nbsp;</th>
                                </thead>
                                <tbody>
                                <form action="{{ route('dishes.detach', $dish->id)}} " method="post">
                                    {{ csrf_field() }}
                                @foreach ($products as $product)
                                    <tr>
                                        <td> <a href="{{route('products.show', $product->id) }}">{{ $product->name }}</a></td>
                                        <td> {{ $product->comment }}</td>
                                        <td> {{ $product->pivot->amount }} {{ $product->unit }} </td>
                                        <td> {{ $product->price_single }} Eur/{{$product->unit}}</td>
                                        <td> {{ $product->price_single * $product->pivot->amount }} Eur</td>
                                        <td>
                                            <button name="product" value="{{$product->id}}" type="submit" class="btn btn-danger">Atsegti</button>
                                        </td>
                                    </tr>
                                @endforeach
                                </form>
                                </tbody>
                            </table>
                        @else
                            <p> Patiekalas neturi prisegtų produktų </p>
                        @endif
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Prisegti kitą produktą:</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($all_products->count())
                            <table class="table table-striped">
                                <thead>
                                <th>Pavadinimas</th>
                                <th>Komentaras</th>
                                <th>Kiekis</th>
                                <th>&nbsp;</th>
                                </thead>
                                <tbody>
                                <form action="{{ route('dishes.attach', $dish->id)}}" method="post">
                                    {{ csrf_field() }}
                                @foreach ($all_products as $product)
                                    <tr>
                                        <td> <a href="{{route('products.show', $product->id) }}">{{ $product->name }}</a></td>
                                        <td> {{ $product->comment }}</td>
                                        <td>
                                            <div class="number-input">
                                                <input type="number" class="form-control input-sm" name="amount-{{ $product->id }}" id="amount-{{ $product->id }}">
                                                <span>{{ $product->unit }}</span>
                                            </div>
                                        </td>
                                        <td>
                                            <button name="product" value="{{$product->id}}" type="submit" class="btn btn-danger">Prisegti</button>
                                        </td>
                                    </tr>
                                @endforeach
                                </form>
                                </tbody>
                            </table>
                        @else
                            <p> Nėra kitų produktų </p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection